create table if not exists public.assessment_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  company text not null,
  email text not null,
  units text,
  score integer not null check (score between 0 and 100),
  tier text not null,
  opportunities jsonb not null default '[]'::jsonb,
  answers jsonb not null default '[]'::jsonb,
  source text not null default 'website-ai-readiness-assessment'
);

alter table public.assessment_leads enable row level security;

-- The website API writes with the Supabase service-role key.
-- Do not expose that key in browser code.
